/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.finagent.config;
import cn.zhuatech.finagent.model.*; import cn.zhuatech.finagent.repository.*; import org.springframework.boot.CommandLineRunner; import org.springframework.context.annotation.*; import org.springframework.security.crypto.password.PasswordEncoder; import java.time.LocalDate; import java.util.List;
@Configuration public class DataInitializer {@Bean CommandLineRunner seed(OperatingUnitRepository units,WorkRecordRepository records,ResourceRegisterRepository resources,ReviewRecordRepository reviews,UserRepository users,PasswordEncoder encoder){return args->{if(units.count()>0)return;
 OperatingUnit ledger=units.save(new OperatingUnit("FIN-LEDGER","总账与月结组","财务共享中心",5200)),recon=units.save(new OperatingUnit("FIN-RECON","资金与对账组","资金管理中心",4200)),expense=units.save(new OperatingUnit("FIN-EXPENSE","费用审核组","财务运营中心",3000));
 WorkRecord a=records.save(new WorkRecord("CLOSE-2608-014","LEDGER-202608","八月月结勾稽与差异解释",ledger,156,108,4,LocalDate.now().plusDays(1),WorkRecord.Status.RUNNING,"POLICY-2026.6")); WorkRecord b=records.save(new WorkRecord("RECON-2608-027","BANK-ICBC-01","工商银行主账户自动对账",recon,128,128,2,LocalDate.now(),WorkRecord.Status.COMPLETED,"RULESET-V8")); WorkRecord c=records.save(new WorkRecord("EXP-2608-041","COST-MKT-03","市场活动费用合规抽查",expense,94,52,7,LocalDate.now().plusDays(2),WorkRecord.Status.RELEASED,"POLICY-2026.4"));
 resources.saveAll(List.of(new ResourceRegister("DATA-GL-01","总账数据连接",ledger,ResourceRegister.Status.RUNNING,98),new ResourceRegister("DATA-BANK-02","银企回单通道",recon,ResourceRegister.Status.RUNNING,95),new ResourceRegister("RULE-FIN-03","财务政策规则库",expense,ResourceRegister.Status.ALARM,79)));
 reviews.saveAll(List.of(new ReviewRecord("CHECK-260801-014",a,"月结完整性",32,2,ReviewRecord.Result.PENDING,"程璟"),new ReviewRecord("CHECK-260801-009",b,"对账准确性",28,0,ReviewRecord.Result.PASSED,"苏禾"),new ReviewRecord("CHECK-260731-036",c,"费用政策命中",24,4,ReviewRecord.Result.FAILED,"宋惟")));
 String demo=encoder.encode("Demo@2026"); users.saveAll(List.of(new UserAccount("operator",demo,"苏禾",UserAccount.Role.DOMAIN_USER,"FIN-LEDGER"),new UserAccount("planner",demo,"程璟",UserAccount.Role.DOMAIN_OPERATOR,null),new UserAccount("quality",demo,"宋惟",UserAccount.Role.QUALITY,null),new UserAccount("admin",encoder.encode("ZhuaTech@2026"),"系统管理员",UserAccount.Role.ADMIN,null)));};}}
