/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.finagent.controller;import cn.zhuatech.finagent.common.ApiResponse;import cn.zhuatech.finagent.service.JournalProposalReleaseService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                           */
@RestController @RequestMapping("/api/enterprise/finagent")public class JournalProposalReleaseController{private final JournalProposalReleaseService service;/**
                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                        */
public JournalProposalReleaseController(JournalProposalReleaseService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
@PostMapping("/journal-proposal-release")public ApiResponse<JournalProposalReleaseService.Assessment>assess(@Valid @RequestBody JournalProposalReleaseService.Request request){return ApiResponse.ok(service.assess(request));}}
