/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.finagent.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                 */
class JournalProposalReleaseServiceTest{private final JournalProposalReleaseService s=new JournalProposalReleaseService();/**
                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                           */
@Test void postsControlledJournal(){var r=s.assess(new JournalProposalReleaseService.Request("J1",true,true,true,true,true,true,false,true,true,true,true,true));assertThat(r.decision()).isEqualTo(JournalProposalReleaseService.Decision.POST);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
@Test void reviewsAuditAndReversal(){var r=s.assess(new JournalProposalReleaseService.Request("J2",true,true,true,true,true,true,false,false,false,false,false,true));assertThat(r.actions()).hasSize(2);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
@Test void blocksUnsafeJournal(){var r=s.assess(new JournalProposalReleaseService.Request("J3",false,false,false,false,false,false,true,true,false,true,true,false));assertThat(r.blockers()).hasSize(9);}}
